version: '2'

services:
  nginx:
    image: nginx
    container_name: hma_web
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - hma_www:/html
  php:
    image: php:fpm
    container_name: hma_web_php
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - hma_www:/html
  openhab:
    image: "openhab/openhab:2.0.0-amd64"
    container_name: hma_openhab
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    ports:
      - "9125:9125"
      - "9126:9126"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - hma_openhab_config:/openhab/conf
      - hma_openhab_rrd4j:/openhab/userdata/persistence/rrd4j
      - hma_openhab_log:/openhab/userdata/logs
      - ./backup:/backups
  influxdb:
    image: influxdb
    container_name: hma_influxdb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - hma_influxdb:/var/lib/influxdb
      - ./backup:/backups
    restart: always
  grafana:
    image: grafana/grafana
    container_name: hma_grafana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - hma_grafana:/var/lib/grafana
      - ./backup:/backups
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "${HOSTNAME}"
      GF_SERVER_ROOT_URL: "http://${HOSTNAME}:3000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  mosquitto:
    image: toke/mosquitto
    container_name: hma_mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
  hma_www:
  hma_openhab_config:
  hma_openhab_rrd4j:
  hma_openhab_log:
  hma_grafana:
  hma_influxdb:
