version: '2'

services:
  nginx:
    image: nginx
    container_name: hma_web
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/Library/Docker/OpenHAB/Nginx/www:/html:ro
      - ~/Library/Docker/OpenHAB/Nginx/nginx-ssl.crt:/etc/nginx/chained.crt:ro
      - ~/Library/Docker/OpenHAB/Nginx/nginx-ssl.key:/etc/nginx/key.key:ro
      - ~/Library/Docker/OpenHAB/Nginx/htpasswd:/etc/nginx/htpasswd:ro
  php:
    image: php:fpm
    container_name: hma_web_php
    restart: always
    volumes:
      - ~/Library/Docker/OpenHAB/Nginx/www:/html  
  openhab:
    image: "openhab/openhab:2.1.0-amd64-debian"
    container_name: hma_openhab
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    ports:
      - "9125-9135:9125-9135"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ~/Library/Docker/OpenHAB/OpenHAB/config:/openhab/conf
      - ~/Library/Docker/OpenHAB/OpenHAB/persist:/openhab/userdata/persistence
      - hma_openhab_log:/openhab/userdata/logs
      - ./backup:/backups
  frontail:
    image: mthenw/frontail
    container_name: hma_frontail
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - hma_openhab_log:/log:ro
      - ./frontail-theme.css:/usr/lib/node_modules/frontail/lib/web/assets/styles/openhab.css:ro
      - ./frontail-preset.json:/preset/openhab.json:ro
    command: "-p 8001 --ui-highlight --ui-highlight-preset /preset/openhab.json -t openhab /log/openhab.log /log/events.log"
  influxdb:
    image: influxdb
    container_name: hma_influxdb
    volumes:
      - ~/Library/Docker/OpenHAB/InfluxDB:/var/lib/influxdb
      - ./backup:/backups
    restart: always
  grafana:
    image: grafana/grafana
    container_name: hma_grafana
    restart: always
    volumes:
      - ~/Library/Docker/OpenHAB/Grafana:/var/lib/grafana
      - ./backup:/backups
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "${HOSTNAME}"
      GF_SERVER_ROOT_URL: "http://${HOSTNAME}:3000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_BASIC_ENABLED: "false"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  mosquitto:
    image: toke/mosquitto
    container_name: hma_mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
volumes:
  hma_openhab_log: