version: '2'

services:
  nginx:
    image: nginx
    container_name: hma_web
    depends_on:
      - php
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sample-conf/Nginx/www:/html
  php:
    image: php:fpm
    container_name: hma_web_php
    restart: always
    volumes:
      - ./sample-conf/Nginx/www:/html
  openhab:
    image: "openhab/openhab:2.1.0-amd64"
    container_name: hma_openhab
    depends_on:
      - influxdb
      - mosquitto
    restart: always
    ports:
      - "9125:9125"
      - "9126:9126"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./timezone:/etc/timezone:ro
      - ./sample-conf/OpenHAB/config:/openhab/conf
      - ./sample-conf/OpenHAB/log:/openhab/userdata/logs
      - ./backup:/backups
  influxdb:
    image: influxdb
    container_name: hma_influxdb
    volumes:
      - ./backup:/backups
    restart: always
  grafana:
    image: grafana/grafana
    container_name: hma_grafana
    restart: always
    volumes:
      - ./backup:/backups
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_DOMAIN: "${HOSTNAME}"
      GF_SERVER_ROOT_URL: "http://${HOSTNAME}:3000/grafana"
      GF_USERS_DEFAULT_THEME: "light"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  mosquitto:
    image: toke/mosquitto
    container_name: hma_mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
